const mongoose = require('mongoose');

const employeeMessageSchema = new mongoose.Schema({
  employeeId: {
    type: String,
    required: true,
    index: true
  },
  employeeUserId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee',
    required: false
  },
  sender: {
    type: String,
    required: true,
    default: 'Company Admin'
  },
  category: {
    type: String,
    enum: ['performance', 'attendance', 'meeting', 'weather', 'suggestion', 'info'],
    required: true
  },
  title: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  },
  messageText: {
    type: String,
    required: true
  },
  readStatus: {
    type: Boolean,
    default: false,
    index: true
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  important: {
    type: Boolean,
    default: false
  },
  metadata: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  },
  timestamp: {
    type: Date,
    default: Date.now,
    index: true
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  },
  readAt: {
    type: Date,
    default: null
  }
}, { collection: 'employeemessages' });

employeeMessageSchema.index({ employeeId: 1, timestamp: -1 });
employeeMessageSchema.index({ readStatus: 1, timestamp: -1 });
employeeMessageSchema.index({ employeeId: 1, readStatus: 1 });

// Ensure messageText is always set from message field
employeeMessageSchema.pre('save', function(next) {
  if (this.isModified('message') && !this.messageText) {
    this.messageText = this.message;
  }
  if (!this.timestamp) {
    this.timestamp = this.createdAt || new Date();
  }
  next();
});

module.exports = mongoose.model('EmployeeMessage', employeeMessageSchema);
